BEGIN;

CREATE TABLE events (
    event_id UUID PRIMARY KEY,
    run_id UUID NOT NULL,
    agent_execution_id UUID NOT NULL,
    session_id TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    sequence_number BIGINT NOT NULL CHECK (sequence_number >= 0),
    event_type TEXT NOT NULL CHECK (length(trim(event_type)) > 0),
    trace_id TEXT,
    span_id TEXT,
    parent_span_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(metadata) = 'object'),
    schema_version INTEGER NOT NULL DEFAULT 1 CHECK (schema_version > 0),
    FOREIGN KEY (run_id, agent_execution_id)
        REFERENCES agent_executions (run_id, agent_execution_id),
    UNIQUE (run_id, event_id),
    UNIQUE (agent_execution_id, sequence_number)
);

CREATE INDEX events_run_time_idx ON events (run_id, occurred_at, event_id);
CREATE INDEX events_run_type_idx ON events (run_id, event_type);
CREATE INDEX events_trace_span_idx ON events (trace_id, span_id)
    WHERE trace_id IS NOT NULL;

COMMENT ON COLUMN events.event_id IS
    'Generated by the producer before delivery. Retry identical payloads with this same ID; ingest with ON CONFLICT (event_id) DO NOTHING.';
COMMENT ON COLUMN events.sequence_number IS
    'Producer-assigned local order within an agent execution, preserved on retry. Not a global or causal order.';
COMMENT ON COLUMN events.metadata IS
    'Redacted event-specific evidence from instrumentation or application code. Large payloads use artifact references; observer conclusions are stored separately.';
COMMENT ON COLUMN events.session_id IS
    'Optional external browser/session identifier; not the workflow run ID.';
COMMENT ON COLUMN events.parent_span_id IS
    'Optional external tracing relationship. No foreign key: parent telemetry may arrive later or be unavailable.';

-- Enforce append-only evidence. Deletion/retention requires a separate deliberate policy.
CREATE FUNCTION reject_event_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Execution events are immutable; insert a new event instead';
END;
$$;

CREATE TRIGGER events_reject_update
    BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION reject_event_update();

COMMIT;
